### ISSUE TITLE
Meguro.rb#19 at Quipper 2018/09/27 (木)

### ISSUE THREAD

**Issue by ohbarye** [megurorb/organizers#37]
## 開催日
* 毎月第四木曜日
  * ただし、会場の都合などで難しければズラす

## 事前準備
* connpass でイベント作成 at 2週間前くらい
  * スライドは発表後にアップしてほしいと記載
* event を SNS などで告知 at 適宜
* ご飯・飲み物の手配 at 前日まで
* 当日の役割分担決め at 当日まで

## 当日会場準備
* ネームカード準備（必要な場合）
  * [参加者の名は](https://yoshiko-pg.github.io/your-name/) を第4回では利用
* Wifi 準備 & 周知方法決めておく（スライド or ホワイトボード）
* 発表できる環境（プロジェクター、座席）
* クロークの準備
* 飲み物をデリバリー
* 受付設置
  * 名簿作成（管理するなら）

## 当日の役割
* 会場準備（プロジェクター、座席、受付、会場を伝える張り紙、飲み物、食べ物、etc...）
* 受付（開始 30 分前 ~ 30分後までが目安。それ以降は受付なしで勝手に入ってきてもらう）
  * クロークの案内もする
* 司会（Opening Talk、LT、質問タイム、自己紹介タイムの進行）
  *  [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) も参考にしてください
* タイムキーパー（終了2分前と終了時間を知らせる）
* SNS実況&写真係（公式アカウントなど）
  * [meguro.rb公式アカウント](https://www.google.co.jp/search?q=twitter+megurorb&oq=twitter+megurorb&aqs=chrome..69i57j69i60l3j69i64.2043j0j7&sourceid=chrome&ie=UTF-8)は[TweetDeck](https://tweetdeck.twitter.com/)で管理

## OpningTalk について
* [Meguro.rb Opening Talkスライド](https://drive.google.com/drive/folders/0BxCKnEOd8gJ-VDQ3RGM1dXAyWk0) に過去のスライドが溜まってます
* 以下を盛り込むと良いと思います
  * Meguro.rb の説明
  * Twitter ハッシュタグ #megurorb でツイートしてもらうこと
  * タイムキーパーの存在
  * Talk 終わりの質問タイム

## 会場にあると良い設備
* マイクピン or マイクスタンド（手を使いたい人向け）

## ロゴなどの Asset
- [brand-assets](https://github.com/megurorb/organizers/tree/master/brand-assets) から利用

## イベントページ  Template
Connpass に作成するイベントページの Template です。作成の際は適宜書き換えてお使いください。

https://github.com/megurorb/organizers/blob/master/connpass_template.md

## 各種SNSアカウント
- connpass https://megurorb.connpass.com
- twitter https://tweetdeck.twitter.com
- facebook https://www.facebook.com/megurorb
- github https://github.com/megurorb

**Comment by ohbarye** [comment]
## ToDo

- [x] イベントページ公開
   - [x] connpass で作成 https://megurorb.connpass.com/event/100401/
   - [x] Twitter で告知 https://mobile.twitter.com/megurorb/status/1036804085444308992
   - [x] Facebook で告知 https://www.facebook.com/megurorb/
- [ ] (TBA)

**Comment by ohbarye** [comment]
# 振り返り

## K

- 前回課題だった集客が良かった
   - 公開から一日の間に19人の申し込みがあり、10分トーク枠5本は埋まってしまった
   ![image](https://user-images.githubusercontent.com/1811616/45266069-47576400-b490-11e8-9fce-d028781ceabe.png)
- LT10本の形式に挑戦してみた
   - 切り替え判断が早かった

## P

## T

**Comment by ohbarye** [comment]
イベント趣旨とか関係なくとりあえずおもいつき。あとで追記、修正します


## K

- イベント準備
  - 前回課題だった集客が良かった
  - 公開から一日の間に19人の申し込みがあり、10分トーク枠5本は埋まった
  ![image](https://user-images.githubusercontent.com/1811616/45266069-47576400-b490-11e8-9fce-d028781ceabe.png)
- イベント形式
  - LT10本の形式に挑戦してみた
    - 切り替え判断が早かった
    - LT形式よかった。さくさく進んだし、登壇者が多いことで懇親会が弾みやすくなる(たぶん
  - 申し込みぎりぎりになる前（開催1週間前ぐらい）に増枠判断ができた
- イベント当日
  - エンゲージメント
    - イベント参加率が高かった(8~9割来ていた)
    - 懇親会参加率が高かった(懇親会前に帰られた方は1名だけ)
  - 食料
    - 準備
      - 料理がちゃんと開催直後にリリースされた
      - 料理の内容はもちろんだけど、まずはこの基本中の基本を抑えてるのが大事
    - 内容
      - サンマがよかった。新規性もあったし目黒のさんまLTと繋がった
      - トルティーヤがよかった。新規性もあったし、時間はかかっても巻く工程を参加者が楽しめた
      - 追い飯の判断ができてよかった。追い飯も全部ハケたので買ってよかった
  - 会場案内
    - 入退館でトラブルがなかった
    - 初対面どうしで名札が役に立っていた
  - 登壇者視点
    - LTのタイムキープが良かった
    - ラップトップによる残り時間表示
    - 5分経過時のチンベル
  - タイムキープ
    - できていて良かった
    - ただし @chaspy さんのLTが3分で終わったりのおかげで巻いた説はある。後半は10分弱押した

## P
- イベント準備
  - 会場設営
    - 椅子を並べすぎて通路がなく、前の方に座った人が出られなかった(休憩のタイミングで真ん中に通路つくった
- イベント当日
  - エンゲージメント
    - 懇親会でぼっちになっている方を見かけたので、パックマンルールのようなものを設けたらより会話に参加しやすかったかも
    - 自己紹介タイムを削ったために話す糸口を失ったかも
    - 自己紹介タイムがなかった（有名人LTする人以外にも結構きてた印象だが顔名前一致させられなかった）
      - マイクを渡されたら自動的に自己紹介する、みたいなルールがあれば回ったかもしれない
  - 食料
    - ご飯食べられなかった人がちらほら。予算の関係もあるけどちょっと余るくらいがちょうど良い説はある気がする
    - 飲食物のキャパシティプランニングを誤って追い飯の必要性が生じた
  - 会場案内
    - 受付がスルーされがちで気付かずに入っていく人がそこそこいた
    - 最初の案内スライドをどこかに常時表示できれば良かった
      - 遅れてきた人(いたのかな？)はWi-Fi情報などを知るすべがなかったかも？
  - LTの合間の無音がやや苦しい
     - 司会がつなぐか、音楽かCMがあると新規性ある
  - タイムキープ
    - 参加者も見える位置にタイマー置いたつもりだったが特にアナウンスはしてなかったしちょうど司会台のせいでみえなかった人がいた


## T

- パックマンルールとか
- このノリでquipper.vimも開催する
- ブリを捌く
- Wifiわからない問題を解消するとしたら
  - 名刺を事前に印刷してWifi情報/Twitterハッシュタグをそこに載せる（大規模カンファレンス方式）
  - 2台あるうちの片方を常に司会用にしておく
    - これは会場のセットアップとセットが基本。LT用のスライドが見やすいよう椅子を寄せるべき
    - 椅子のキャパシティ的に片方に寄せるということもやりづらくて悩ましい
- 発表やって終わりという形式でなくフィードバックを得たり発表者以外も参加するための仕組みが会として欲しい
- 時間測るならタイマーは発表者の見えるどっかに表示されてると親切
- スマートな自己紹介
- フィードバックを得やすいしくみ
  - 同期
    - QAタイム
    - Ask the speaker
    - 懇親会で登壇者ごとのテーブル作って歓談とかでもいいかな
  - 非同期
    - アンケート
    - pull request （どこに）

**Comment by ohbarye** [comment]
Quipper社内でのKPTから抜粋したものを貼りました！
https://github.com/megurorb/organizers/issues/37#issuecomment-425936097

これで全タスク終了したのでクローズします。
