### ISSUE TITLE
第1回 Meguro.rb at 3/23 (木)

### ISSUE THREAD

**Issue by south37** [megurorb/organizers#7]
## 日程、会場
* 3/23 (木) 19:30 ~
* Wantedly オフィス

## 内容
* 自己紹介フォーマット
  * TODO(ngtk)
* LT を6人、視聴者 15人くらい
* 飲み物食べ物あり、参加費500円（出来れば次回から持ち回りにしたい）

## スケジュール
19:00 開場
19:30 乾杯
19:30 - 20:00 自己紹介
20:00 - 21:00 LT (10m x 6)
21:00  - 22:00  懇親タイム(Sushi)

## 事前準備
* minami, nagata は発表
    * [x] TODO: +3人社外から連れてくる by 南、永田
        * 期限は 3/10（金）
* [x] connpass でグループ作成
  * https://megurorb.connpass.com/
* [x] connpass でイベント作成 by 永田
  * 公開は3/10(金)
* [x] ご飯・飲み物を用意 by wantedly
* [x] かっこいいロゴ by @maosugaya 
~~* [ ] github.io 刷新 @south37 @ngtk at 3/10（金）~~

## 管理アカウント 
- connpass https://megurorb.connpass.com/
- twitter https://twitter.com/megurorb
- facebook https://www.facebook.com/megurorb/
- github https://github.com/megurorb

## 巻き込み対象
* [x] ドリコム @south37
~~* [ ] リブセンス @south37~~
~~* [ ] エウレカ @ngtk~~
* [x] Viibar @ngtk 

## 参考: 目黒スタートアップ勉強会 
https://connpass.com/event/14407/participation/

**Comment by south37** [comment]
## その他内容アイディアメモ
* 少人数で全員LT(10人弱のイメージ)
    * おつまみを持ち寄ってビールを飲みまくる（Tokyu.rb スタイル）
* 割と長めの発表 （Tokyo.rb スタイル）
* 課題を用意してみんながコードを書く（Cookpad スタイル）
* LT そこそこ、聴く人いっぱい（10人弱発表、20人くらい聞いてる）
* もくもく会
* コードリーティング会
    * 1人が事前に読んで準備
    * cf. https://github.com/wantedly/code-reading
* 速習会

**Comment by south37** [comment]
## 弊社デザイナーによるロゴ案
@ngtk 
速攻一個作ってみた。

<img width="1280" alt="1 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602326/5e4f4142-0293-11e7-81b3-d2bc90a2ab56.png">
<img width="1280" alt="2 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602325/5e4d5e22-0293-11e7-974e-9936c41b6460.png">
<img width="1280" alt="3 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602323/5e472d86-0293-11e7-8634-2077901bcef1.png">
<img width="1280" alt="4 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602324/5e4a40f2-0293-11e7-8ee6-3978a4fe04e2.png">
<img width="1280" alt="5 2x" src="https://cloud.githubusercontent.com/assets/5927494/23602327/5e5d8018-0293-11e7-8de5-5b4be7601676.png">

**Comment by ngtk** [comment]
## Connpass event description draft
For https://connpass.com/event/52592/edit/

* 概要
	* Meouro.rbは復活しました！
	* RubyやRuby周辺の技術好きのための地域コミュニティー
	* 第一回は2017/03/23(木) 19:30 @ Wantedly
	* 寿司
	* 参加費は500円
	* 今回はLTをメインでやります
	* まだ第一回ですので、今後の会のスタイルはぜひぜひ提案してください！一緒に盛り上げましょう！
* スケジュール
	* 19:00 開場
	* 19:30 乾杯
	* 19:30 - 20:00 自己紹介
	* 20:00 - 21:00 LT (10m x 6)
	* 21:00  - 22:00  懇親タイム(Sushi)
* LT
	* 発表者名とタイトル(?)
* 会場
	* [全員向け] 住所
	* [全員向け] 飲食可能かどうか
		* 可能
	* [全員向け] ネットワーク(wi-fi)があるかどうか
		* ゲストwi-fiがあります
	* [全員向け] 電源があるかどうか
		* 数が限られていますが、あります
	* [発表者向け] 対応可能な入力端子(プロジェクタ)
		* HDMI または thunderboltのみ対応可能です。他をご希望の場合は変換アダプタをご持参ください。
* 注意事項
	* 撮影は禁止ではありませんが、被写体に許可をとってください
* FAQ(あれば)
* ソーシャルリンク
	* Twitter
	* Facebook

**Comment by ngtk** [comment]
デザイン系は #9 に切り出しました。

**Comment by luvtechno** [comment]
connpass で設定しているTwitterハッシュタグは `#ruby` より `#megurorb` のほうがよいのではないかと思います。

**Comment by ngtk** [comment]
> connpass で設定しているTwitterハッシュタグは #ruby より #megurorb のほうがよいのではないかと思います。

そうですね！変更しました！ 😃 
https://megurorb.connpass.com/event/52592/

**Comment by ngtk** [comment]
## 当日の詳細
### 準備するもの
cc: @MasahiroInou

- 受付票
- ネームホルダーおよび中の紙(30セット)
- 紙コップ(30個)
- 飲み物(21人分)
- 食べ物(21人部)
- 皿(30個)

### タイムテーブル
cc: @MasahiroInou @south37 

[Spreadsheet](https://docs.google.com/spreadsheets/d/1q3qhk2FU8eJrD6f2ortSla4oa0GtrQWFmr9NXAR5jGw/edit#gid=0)

<img width="1102" alt="2017-03-21 15 41 15" src="https://cloud.githubusercontent.com/assets/1107315/24135443/1101be36-0e4d-11e7-9849-cee30b80f85d.png">

**Comment by south37** [comment]
@ngtk 

ありがとう！ 😄 

ちょっと思った事だけど、「自己紹介フォーマット」が定まったら、事前告知して考えて来てもらうのも良いかも？
もしくは、待ってる間にスライドに映しておいて、その間に考えておけるようにしても良いかも！ 💡

**Comment by ngtk** [comment]
@south37 FBありがとう！ 😸 

> ちょっと思った事だけど、「自己紹介フォーマット」が定まったら、事前告知して考えて来てもらうのも良いかも？


そうですね。積極的に告知する感じだと逆にハードル上がる感あるから、commpassの説明文更新くらいで考えていました！

> もしくは、待ってる間にスライドに映しておいて、その間に考えておけるようにしても良いかも！ 💡


これは用意しようと思います！ 👍

**Comment by MasahiroInou** [comment]
本人確認という名目で、一応名刺を貰っておきたいという話になりました。
僕から連絡することは無いと思いますが、南さん、永田さんが後日連絡とりたいとなったときに、なにかと便利だと思うので。

@ngtk 
Connpassに追記お願いできますでしょうか？

※本人確認のため名刺をお持ちください

のような形で。
よろしくお願いします。

**Comment by MasahiroInou** [comment]
https://docs.google.com/spreadsheets/d/1Ig6U9Gw4EbZ4oNZ57Ry6T3q9mz3G5mDjYX51cCcwAyY/edit#gid=0
出欠確認票

**Comment by ngtk** [comment]
@MasahiroInou 

> 本人確認のため、一応名刺を貰っておきたいという話になりました。
僕から連絡することは無いと思いますが、南さん、永田さんが後日連絡とりたいとなったときに、なにかと便利だと思うので。
> Connpassに追記お願いできますでしょうか？

たしかに。了解です！

**Comment by ngtk** [comment]
✅ 名刺持参について追記&コメント

<img width="679" alt="2017-03-22 10 06 16" src="https://cloud.githubusercontent.com/assets/1107315/24177655/51a5a8ea-0ee7-11e7-9368-b54402c1c4df.png">

**Comment by ngtk** [comment]
# KPT 
## MEMO
* １人単価 1,000円

## TODO
* まとめエントリーを書く @south37 
* 資料をあげてもらう(今度からは当日発表後にアップロード)


## PROBREM
* クロークを考えていなかった
* ビールが冷えてなかった問題
* タイムキーパーが欲しい


## KEEP
* 寿司
* 自己紹介コーナー


## TRY
* 1週間前までにタイトルないしテーマを書いて、再告知をしたほうが良いかも
* LTじゃない形式をやってみたい
* ソーシャル拡散するように誘導したほうが良かった

**Comment by umanoda** [comment]
昨日はありがとうございました！ 素敵なオフィスでした ✨ ✨ 

個人的な感想というか、こうだったら良かったな系のやつあげてみます

* タイムキーパーは確かに欲しかった
* 飲み物、食べ物の置き場所
  * みんなが座る場所の後ろなどにテーブルを置いて、そこに飲み物などあったほうが気軽に取れる
  * 寿司を取るテーブルに人があつまって、話しながら手を伸ばすというのができなかった

個人的な反省点は、せっかくの懇談会で一部の人とだけ話して終わってしまった…！
がんばらねば… 😖

**Comment by ngtk** [comment]
> みんなが座る場所の後ろなどにテーブルを置いて、そこに飲み物などあったほうが気軽に取れる
寿司を取るテーブルに人があつまって、話しながら手を伸ばすというのができなかった

たしかにですね！FBありがとうございます！

**Comment by south37** [comment]
## 残りTODO
- [ ] 第一回Meguro.rb やりました報告
  - Twitter, Facebook, 公式ページ
  - 当日の写真をもし誰か撮ってたら欲しい。。。。

## 次回以降やると良さそうな事
- リアルタイムでのソーシャル拡散
  - Twitter 実況とか、hashtag 伝えてやりやすい形にするとかは出来るかも（後でまとめとかにもしやすい）
- 当日の写真を撮りまくる

**Comment by MasahiroInou** [comment]
写真何枚かあるので、あとで共有します！

**Comment by luvtechno** [comment]
> リアルタイムでのソーシャル拡散
> 当日の写真をもし誰か撮ってたら欲しい。。。。

そういえば、「写真の撮影は被写体の許可をとってから」というアナウンスがあったので、実際写真がとりにくかったです。実質撮影禁止に近い連絡だと思いました。

- 写真が撮られることがあります
- 撮影NGの人は事前に申し出てください

のどちらかを参加募集ページに記載する運用ができると、ソーシャルで使うのによさそうです。

**Comment by ngtk** [comment]
> そういえば、「写真の撮影は被写体の許可をとってから」というアナウンスがあったので、実際写真がとりにくかったです。実質撮影禁止に近い連絡だと思いました。

そうですね。

> 撮影NGの人は事前に申し出てください

この運用がいいかなと思いました。
最初のアナウンスで申し出てもらえれば、みんなもやりやすいかもです。

**Comment by MasahiroInou** [comment]
第二回についてWantedly Newsでサラッと触れたいのですが、二回目は会場ドリコムさんでやることまで決定でしょうか？

**Comment by south37** [comment]
@MasahiroInou 「二回目は会場ドリコムさんで4月にやること」まで決定です！ 👍

**Comment by MasahiroInou** [comment]
@south37 
ありがとうございます☺

**Comment by ngtk** [comment]
ちゃんと振り返りまでできたのでクローズ。
